---
title: hi my study
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: vusvus777@gmail.com
description: wow hi my name is choi
baseurl: ''
url: ''
twitter_username: pi
github_username: pi
theme: minima
plugins:
- jekyll-feed
